version: '3.8'

services:

  mongo:
    hostname:       ${NAME}-mongo
    container_name: ${NAME}-mongo
    image: mongo:4.4.3-bionic
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./docker/mongo/db:/data/db
      # Guardar configuracion de la base de datos
      # - ./docker/mongo/configdb:/data/configdb

  mongo-express:
    hostname:       ${NAME}-mongo-express
    container_name: ${NAME}-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  node:
    hostname:       ${NAME}-node
    container_name: ${NAME}-node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    command: node server.js
    # volumes: 
      # - ./server:/usr/src/app
    ports: 
      - ${NODE_PORT}:8080