version: '3.8'

services:

  mongo:
    hostname:       ${NAME}-mongo
    container_name: ${NAME}-mongo
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./docker/mongo/db:/data/db
      # Guardar configuracion de la base de datos
      # - ./docker/mongo/configdb:/data/configdb

  mongo-express:
    hostname:       ${NAME}-mongo-express
    container_name: ${NAME}-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}